name: Continuous Integration

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.5"

    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      # This is a *hack* to install all runtime/test deps without running the
      # tests. The idea is to have a better output when there is some error
      # on dependency installation
      run: luarocks test -- --version

    - name: Run tests
      run: luarocks test
